.\" man page create by R# package system.
.TH CFD 1 2000-Jan "dump_stream" "dump_stream"
.SH NAME
dump_stream \- export the simulation result as image frames
.SH SYNOPSIS
\fIdump_stream(\fBpack\fR as <generic> FrameReader, 
\fBfs\fR as any, 
\fBdimension\fR as string = "speed2", 
\fBcolors\fR as any = "viridis", 
\fBcolor_levels\fR as integer = 200, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
export the simulation result as image frames
.PP
.SH OPTIONS
.PP
\fBpack\fB \fR\- -. 
.PP
.PP
\fBfs\fB \fR\- -. 
.PP
.PP
\fBdimension\fB \fR\- -. 
.PP
.PP
\fBcolors\fB \fR\- -. 
.PP
.PP
\fBcolor_levels\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
CFD
.SH FILES
.PP
CFD_clr.dll
.PP
